In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./friends.jpg')

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
#Load CascadeClassifier
haar = cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')

In [7]:
#step 1 : Convert Image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#step 2 : Apply gray scale to cascade classifier
face_rect = haar.detectMultiScale(gray, 1.3, 5)


In [8]:
print(face_rect)

[[165 140 130 130]
 [335 118 125 125]
 [531 120 127 127]]


In [10]:
image = img.copy()

#step3 : draw boumding box
for x,y,w,h in face_rect:
    cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)

cv2.imshow('detector faces', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Real time face detection using OpenCV


In [25]:
cap = cv2.VideoCapture('./video.mp4')
if not cap.isOpened():
        raise FileNotFoundError(f"Could not open video: {video_path}")
try:
    while True:
        ret, frame = cap.read()
        if ret == False:
            print("End of video or error reading frame.")
            break
        
        image = frame.copy()
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        face_rect = haar.detectMultiScale(gray, 1.3, 5)
        
        for x,y,w,h in face_rect:
            cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)
        
        cv2.imshow('Face detection', image)
    
        if cv2.waitKey(10) == 27:
            break
finally:
    cap.release()
    cv2.destroyAllWindows()
    print("Cleanup completed.")

Cleanup completed.
